#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# homebrew installs stuff under /usr/local/bin (instead of /usr/bin) so we need
# to put that path first in order to actually use what brew installed
export PATH="/usr/local/bin:$PATH"

# tell prezto where python is installed for the virtualenvwrapper plugin
export VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Source virtualenvwrapper
export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/dev/src
source /usr/local/bin/virtualenvwrapper.sh
